import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Mycoin.module.css";
import firebase from "../config/firebase";
import React, { useState, useEffect } from "react";

export default function Home() {
  const [triggerpermission, setTriggerpermission] = useState(3);
  useEffect(() => {
    firebase
      .firestore()
      .collection("triggerID")
      .doc("TriggerPermission")
      .onSnapshot((documentSnapshot) => {
        // console.log("DOCSNAP " + JSON.stringify(documentSnapshot));
        console.log("DOCSNAP " + JSON.stringify(documentSnapshot.data()));
        console.log("DOCSNAP " + documentSnapshot.data().permissionID);
        let permissionID = documentSnapshot.data().permissionID;
        setTriggerpermission(permissionID);
      });
  }, []);

  return (
    <>
      {triggerpermission == 0 ? (
        <>
          <div className={styles.containerwait}>
            <main className={styles.mainwait}>
              <h1 className={styles.titlewait}>
                Please{" "}
                <Link href="https://liff.line.me/1656198560-ZDDm059o">
                  <a>Register</a>
                </Link>
              </h1>
            </main>
          </div>
        </>
      ) : (
        <>
          {triggerpermission == 1 ? (
            <>
              <div className={styles.container}>
                <Head>
                  <title>Coins</title>
                  <meta
                    name="description"
                    content="Generated by create next app"
                  />
                  <link rel="icon" href="/favicon.ico" />
                </Head>
                <div className={styles.header}>
                  <h4 className={styles.headertitle}>COINS</h4>
                </div>
                <div className={styles.leaderboard}></div>
                <main className={styles.main}>
                  <div className={styles.leadercard}>
                    <div className={styles.imagewrap}>
                      <img src="/coinicon1.png"></img>
                    </div>
                    <div className={styles.textwrap}>
                      {/* <p className={styles.textpodcast}>
                        <span>Popquiz</span>
                      </p>
                      <p className={styles.textmainpodcast}>
                        ตอบคำถามชิงรางวัล วันที่ <span>12 Aug 2021</span>
                      </p> */}
                      <p>
                        <span>Popquiz</span> ตอบคำถามชิงรางวัล วันที่{" "}
                        <span>12 Aug 2021</span>
                      </p>
                    </div>
                    <div className={styles.bluewrap}>
                      <p>100 Coins</p>
                    </div>
                  </div>

                  <div className={styles.leadercard}>
                    <div className={styles.imagewrap}>
                      <img src="/coinicon2.png"></img>
                    </div>
                    <div className={styles.textwrap}>
                      <p>
                        <span>Podcast</span> ฟังและตอบคำถามชิงรางวัล วันที่{" "}
                        <span>12 Aug 2021</span>
                      </p>
                      {/* <p className={styles.textpodcast}>
                        <span>Podcast</span>
                      </p>
                      <p className={styles.textmainpodcast}>
                        ฟังและตอบคำถามชิงรางวัล วันที่
                        <span> 12 Aug 2021</span>
                      </p> */}
                    </div>
                    <div className={styles.bluewrap}>
                      <p>100 Coins</p>
                    </div>
                  </div>

                  <div className={styles.leadercard}>
                    <div className={styles.imagewrap}>
                      <img src="/coinicon1.png"></img>
                    </div>
                    <div className={styles.textwrap}>
                      {/* <p className={styles.textpodcast}>
                        <span>Popquiz</span>
                      </p>
                      <p className={styles.textmainpodcast}>
                        ตอบคำถามชิงรางวัล วันที่ <span>12 Aug 2021</span>
                      </p> */}
                      <p>
                        <span>Popquiz</span> ตอบคำถามชิงรางวัล วันที่{" "}
                        <span>12 Aug 2021</span>
                      </p>
                    </div>
                    <div className={styles.bluewrap}>
                      <p>100 Coins</p>
                    </div>
                  </div>

                  <div className={styles.leadercard}>
                    <div className={styles.imagewrap}>
                      <img src="/coinicon2.png"></img>
                    </div>
                    <div className={styles.textwrap}>
                      <p>
                        <span>Podcast</span> ฟังและตอบคำถามชิงรางวัล วันที่{" "}
                        <span>12 Aug 2021</span>
                      </p>
                      {/* <p className={styles.textpodcast}>
                        <span>Podcast</span>
                      </p>
                      <p className={styles.textmainpodcast}>
                        ฟังและตอบคำถามชิงรางวัล วันที่
                        <span> 12 Aug 2021</span>
                      </p> */}
                    </div>
                    <div className={styles.bluewrap}>
                      <p>100 Coins</p>
                    </div>
                  </div>

                  <div className={styles.leadercard}>
                    <div className={styles.imagewrap}>
                      <img src="/coinicon1.png"></img>
                    </div>
                    <div className={styles.textwrap}>
                      {/* <p className={styles.textpodcast}>
                        <span>Popquiz</span>
                      </p>
                      <p className={styles.textmainpodcast}>
                        ตอบคำถามชิงรางวัล วันที่ <span>12 Aug 2021</span>
                      </p> */}
                      <p>
                        <span>Popquiz</span> ตอบคำถามชิงรางวัล วันที่{" "}
                        <span>12 Aug 2021</span>
                      </p>
                    </div>
                    <div className={styles.bluewrap}>
                      <p>100 Coins</p>
                    </div>
                  </div>

                  <div className={styles.leadercard}>
                    <div className={styles.imagewrap}>
                      <img src="/coinicon2.png"></img>
                    </div>
                    <div className={styles.textwrap}>
                      <p>
                        <span>Podcast</span> ฟังและตอบคำถามชิงรางวัล วันที่{" "}
                        <span>12 Aug 2021</span>
                      </p>
                      {/* <p className={styles.textpodcast}>
                        <span>Podcast</span>
                      </p>
                      <p className={styles.textmainpodcast}>
                        ฟังและตอบคำถามชิงรางวัล วันที่
                        <span> 12 Aug 2021</span>
                      </p> */}
                    </div>
                    <div className={styles.bluewrap}>
                      <p>100 Coins</p>
                    </div>
                  </div>
                  <div className={styles.leadercard}>
                    <div className={styles.imagewrap}>
                      <img src="/coinicon1.png"></img>
                    </div>
                    <div className={styles.textwrap}>
                      {/* <p className={styles.textpodcast}>
                        <span>Popquiz</span>
                      </p>
                      <p className={styles.textmainpodcast}>
                        ตอบคำถามชิงรางวัล วันที่ <span>12 Aug 2021</span>
                      </p> */}
                      <p>
                        <span>Popquiz</span> ตอบคำถามชิงรางวัล วันที่{" "}
                        <span>12 Aug 2021</span>
                      </p>
                    </div>
                    <div className={styles.bluewrap}>
                      <p>100 Coins</p>
                    </div>
                  </div>

                  <div className={styles.leadercard}>
                    <div className={styles.imagewrap}>
                      <img src="/coinicon2.png"></img>
                    </div>
                    <div className={styles.textwrap}>
                      <p>
                        <span>Podcast</span> ฟังและตอบคำถามชิงรางวัล วันที่{" "}
                        <span>12 Aug 2021</span>
                      </p>
                      {/* <p className={styles.textpodcast}>
                        <span>Podcast</span>
                      </p>
                      <p className={styles.textmainpodcast}>
                        ฟังและตอบคำถามชิงรางวัล วันที่
                        <span> 12 Aug 2021</span>
                      </p> */}
                    </div>
                    <div className={styles.bluewrap}>
                      <p>100 Coins</p>
                    </div>
                  </div>

                  <div className={styles.leadercard}>
                    <div className={styles.imagewrap}>
                      <img src="/coinicon1.png"></img>
                    </div>
                    <div className={styles.textwrap}>
                      {/* <p className={styles.textpodcast}>
                        <span>Popquiz</span>
                      </p>
                      <p className={styles.textmainpodcast}>
                        ตอบคำถามชิงรางวัล วันที่ <span>12 Aug 2021</span>
                      </p> */}
                      <p>
                        <span>Popquiz</span> ตอบคำถามชิงรางวัล วันที่{" "}
                        <span>12 Aug 2021</span>
                      </p>
                    </div>
                    <div className={styles.bluewrap}>
                      <p>100 Coins</p>
                    </div>
                  </div>

                  <div className={styles.leadercard}>
                    <div className={styles.imagewrap}>
                      <img src="/coinicon2.png"></img>
                    </div>
                    <div className={styles.textwrap}>
                      <p>
                        <span>Podcast</span> ฟังและตอบคำถามชิงรางวัล วันที่{" "}
                        <span>12 Aug 2021</span>
                      </p>
                      {/* <p className={styles.textpodcast}>
                        <span>Podcast</span>
                      </p>
                      <p className={styles.textmainpodcast}>
                        ฟังและตอบคำถามชิงรางวัล วันที่
                        <span> 12 Aug 2021</span>
                      </p> */}
                    </div>
                    <div className={styles.bluewrap}>
                      <p>100 Coins</p>
                    </div>
                  </div>

                  <div className={styles.leadercard}>
                    <div className={styles.imagewrap}>
                      <img src="/coinicon1.png"></img>
                    </div>
                    <div className={styles.textwrap}>
                      {/* <p className={styles.textpodcast}>
                        <span>Popquiz</span>
                      </p>
                      <p className={styles.textmainpodcast}>
                        ตอบคำถามชิงรางวัล วันที่ <span>12 Aug 2021</span>
                      </p> */}
                      <p>
                        <span>Popquiz</span> ตอบคำถามชิงรางวัล วันที่{" "}
                        <span>12 Aug 2021</span>
                      </p>
                    </div>
                    <div className={styles.bluewrap}>
                      <p>100 Coins</p>
                    </div>
                  </div>

                  <div className={styles.leadercard}>
                    <div className={styles.imagewrap}>
                      <img src="/coinicon2.png"></img>
                    </div>
                    <div className={styles.textwrap}>
                      <p>
                        <span>Podcast</span> ฟังและตอบคำถามชิงรางวัล วันที่{" "}
                        <span>12 Aug 2021</span>
                      </p>
                      {/* <p className={styles.textpodcast}>
                        <span>Podcast</span>
                      </p>
                      <p className={styles.textmainpodcast}>
                        ฟังและตอบคำถามชิงรางวัล วันที่
                        <span> 12 Aug 2021</span>
                      </p> */}
                    </div>
                    <div className={styles.bluewrap}>
                      <p>100 Coins</p>
                    </div>
                  </div>
                </main>
              </div>
            </>
          ) : (
            <></>
          )}
        </>
      )}
    </>
  );
}
