import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Register.module.css";
import firebase from "../config/firebase";
import React, { useState, useEffect } from "react";
// import liff from "@line/liff";

export default function Register() {
  const [triggerpermission, setTriggerpermission] = useState(0);
  const [typeid, setTypeid] = useState(1);
  const [nowpage, setNowpage] = useState(0);
  const lineliff_init = async() =>{
    const liff = (await import("@line/liff")).default;
          liff.ready.then(async () => {
            if (liff.isLoggedIn()) {
               const profile = await liff.getProfile();
              //  alert("สวัสดี คุณ "+profile.displayName+" !!");
            } else {
              liff.login();
            }
          });
          await liff.init({ liffId: "1656198560-ZDDm059o" });
  }
  useEffect(() => {
    lineliff_init();
    setNowpage(0);
  }, []);

async function sendMsg() {
  try {
    //  await liff.sendMessages([
    //    {
    //      type: "text",
    //      text: "ลงทะเบียนเรียบร้อย!!",
    //    }
    //  ]);
     liff.closeWindow();
  } catch (error) {
    alert(error);
  }
  
}

  const okHandle = () =>{
      //close liff

      
      sendMsg();

  }

  const submitHandle = () => {
    setNowpage(1);
    firebase
      .firestore()
      .collection("triggerID")
      .doc("TriggerPermission")
      .update({
        permissionID: typeid,
      });
  };

  const dropdownHandle = (e) => {
    let selectval = e.target.value;
    setTypeid(parseInt(selectval));
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {nowpage == 0 ? (
          <>
            <div className={styles.imagewrap}>
              {/* <Image
              src="/logo.png"
                alt="Picture of the author"
                width={200}
                height={152}
                priority={true}
              /> */}
              <img src="/logo.png"></img>
            </div>
            <div className={styles.titlewrap}>
              <p className={styles.title}>Welcome to ttb club</p>
              <p className={styles.title}>ลงทะเบียนเพื่อเข้าร่วมกิจกรรม</p>
            </div>

            <div className={styles.inputwrap}>
              <p className={styles.labeltitle}>Employee no.</p>
              <input
                className={styles.field__input}
                type="text"
                name="name"
                placeholder=""
              />
              <p className={styles.labeltitle}>Position</p>
              <select
                className={styles.field__input_dropdown}
                onChange={dropdownHandle}
                name="position"
              >
                <option className={styles.option} value="0"></option>
                <option className={styles.option} value="1">
                  RM 1
                </option>
                <option className={styles.option} value="1">
                  RM 2
                </option>
              </select>
              <p className={styles.labeltitle}>Birthdate</p>
              <input
                type="date"
                className={styles.field__input_datetime}
                name="birthday"
              ></input>
            </div>
            <div>
              <button onClick={submitHandle} className={styles.submutBtn}>
                Register
              </button>
            </div>
          </>
        ) : (
          <>
            <div className={styles.imagewrap}>
              {/* <Image
              src="/logo.png"
                alt="Picture of the author"
                width={200}
                height={152}
                priority={true}
              /> */}
              <img src="/logo.png"></img>
            </div>
            <div className={styles.titlewrap2}>
              <h1 className={styles.title2}>Great!</h1>
              <h4 className={styles.title}>
                Your account has been registered.
              </h4>
              <h4 className={styles.title}>Please wait for confirmation.</h4>
              <h4 className={styles.title}>
                We will let you know within 24 hr.
              </h4>
            </div>
            <div>
              <button onClick={okHandle} className={styles.submutBtn}>
                OK
              </button>
            </div>
          </>
        )}
      </main>
    </div>
  );
}
