import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Register.module.css";
import firebase from "../config/firebase";
import React, { useState, useEffect } from "react";

export default function Register() {
  const [triggerpermission, setTriggerpermission] = useState(0);
  const [typeid, setTypeid] = useState(1);
  const [nowpage, setNowpage] = useState(0);
  useEffect(() => {
    setNowpage(0);
  }, []);

  const okHandle = () =>{
      //close liff
      alert("close Liff")
  }

  const submitHandle = () => {
    setNowpage(1);
    firebase
      .firestore()
      .collection("triggerID")
      .doc("TriggerPermission")
      .update({
        permissionID: typeid,
      });
  };

  const dropdownHandle = (e) => {
    let selectval = e.target.value;
    setTypeid(parseInt(selectval));
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {nowpage == 0 ? (
          <>
            <div className={styles.imagewrap}>
              <Image
                src="/logo.png"
                alt="Picture of the author"
                width={200}
                height={152}
              />
            </div>
            <div className={styles.titlewrap}>
              <p className={styles.title}>Welcome to ttb club</p>
              <p className={styles.title}>ลงทะเบียนเพื่อเข้าร่วมกิจกรรม</p>
            </div>

            <div className={styles.inputwrap}>
              <p className={styles.labeltitle}>Name</p>
              <input
                className={styles.field__input}
                type="text"
                name="name"
                placeholder="Name"
              />
              <p className={styles.labeltitle}>Position</p>
              <select
                className={styles.field__input_dropdown}
                onChange={dropdownHandle}
                name="position"
              >
                <option className={styles.option} value="0">
                  Position
                </option>
                <option className={styles.option} value="1">
                  Position1
                </option>
                <option className={styles.option} value="1">
                  Position2
                </option>
                <option className={styles.option} value="1">
                  Position3
                </option>
              </select>
              <p className={styles.labeltitle}>Birthdate</p>
              <input
                type="date"
                className={styles.field__input_datetime}
                name="birthday"
              ></input>
            </div>
            <div>
              <button onClick={submitHandle} className={styles.submutBtn}>
                Register
              </button>
            </div>
          </>
        ) : (
          <>
            <div className={styles.imagewrap}>
              <Image
                src="/logo.png"
                alt="Picture of the author"
                width={200}
                height={152}
              />
            </div>
            <div className={styles.titlewrap2}>
              <h1 className={styles.title2}>Great!</h1>
              <h4 className={styles.title}>
                Your account has been registered.
              </h4>
              <h4 className={styles.title}>Please wait for confirmation.</h4>
              <h4 className={styles.title}>
                We will let you know within 24 hr.
              </h4>
            </div>
            <div>
              <button onClick={okHandle} className={styles.submutBtn}>
                OK
              </button>
            </div>
          </>
        )}
      </main>
    </div>
  );
}
