import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Reward.module.css";
import firebase from "../config/firebase";
import React, { useState, useEffect } from "react";

export default function Home() {
  const [triggerpermission, setTriggerpermission] = useState(3);
  useEffect(() => {
    firebase
      .firestore()
      .collection("triggerID")
      .doc("TriggerPermission")
      .onSnapshot((documentSnapshot) => {
        // console.log("DOCSNAP " + JSON.stringify(documentSnapshot));
        console.log("DOCSNAP " + JSON.stringify(documentSnapshot.data()));
        console.log("DOCSNAP " + documentSnapshot.data().permissionID);
        let permissionID = documentSnapshot.data().permissionID;
        setTriggerpermission(permissionID);
      });
  }, []);

  return (
    <>
      {triggerpermission == 0 ? (
        <>
          <div className={styles.containerwait}>
            <main className={styles.mainwait}>
              <h1 className={styles.titlewait}>
                Please{" "}
                <Link href="https://liff.line.me/1656198560-ZDDm059o">
                  <a>Register</a>
                </Link>
              </h1>
            </main>
          </div>
        </>
      ) : (
        <>
          {triggerpermission == 1 ? (
            <>
              <div className={styles.container}>
                <Head>
                  <title>Reward</title>
                  <meta
                    name="description"
                    content="Generated by create next app"
                  />
                  <link rel="icon" href="/favicon.ico" />
                </Head>
                <div className={styles.header}>
                  <h4 className={styles.headertitle}>REWARD</h4>
                </div>
                <div className={styles.leaderboard}></div>
                <main className={styles.main}>
                  <div className={styles.row1}>
                    <div className={styles.col1}>
                      <div className={styles.header}>
                        <h4>120 Coins</h4>
                      </div>
                      <div className={styles.content}>
                        <div className={styles.imgwrap}>
                          <img src="/reward1.png"></img>
                        </div>
                        <div className={styles.contentwrap}>
                          <h4 className={styles.contentwraph4}>
                            Expired : 19 Sep 2021
                          </h4>
                          <p className={styles.contentwrapp}>
                            แลกรับบัตรส่วนลด Lazada 1,000 บาท
                          </p>
                          <div className={styles.bluewrap}>
                            <h4>Redeem</h4>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className={styles.col2}>
                      <div className={styles.header}>
                        <h4>120 Coins</h4>
                      </div>
                      <div className={styles.content}>
                        <div className={styles.imgwrap}>
                          <img src="/reward2.png"></img>
                        </div>
                        <div className={styles.contentwrap}>
                          <h4 className={styles.contentwraph4}>
                            Expired : 19 Sep 2021
                          </h4>
                          <p className={styles.contentwrapp}>
                            แลกรับบัตรส่วนลด Lazada 1,000 บาท
                          </p>
                          <div className={styles.bluewrap}>
                            <h4>Redeem</h4>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>

                  <div className={styles.row1}>
                    <div className={styles.col1}>
                      <div className={styles.header}>
                        <h4>120 Coins</h4>
                      </div>
                      <div className={styles.content}>
                        <div className={styles.imgwrap}>
                          <img src="/reward1.png"></img>
                        </div>
                        <div className={styles.contentwrap}>
                          <h4 className={styles.contentwraph4}>
                            Expired : 19 Sep 2021
                          </h4>
                          <p className={styles.contentwrapp}>
                            แลกรับบัตรส่วนลด Lazada 1,000 บาท
                          </p>
                          <div className={styles.bluewrap}>
                            <h4>Redeem</h4>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className={styles.col2}>
                      <div className={styles.header}>
                        <h4>120 Coins</h4>
                      </div>
                      <div className={styles.content}>
                        <div className={styles.imgwrap}>
                          <img src="/reward2.png"></img>
                        </div>
                        <div className={styles.contentwrap}>
                          <h4 className={styles.contentwraph4}>
                            Expired : 19 Sep 2021
                          </h4>
                          <p className={styles.contentwrapp}>
                            แลกรับบัตรส่วนลด Lazada 1,000 บาท
                          </p>
                          <div className={styles.bluewrap}>
                            <h4>Redeem</h4>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </main>
              </div>
            </>
          ) : (
            <></>
          )}
        </>
      )}
    </>
  );
}
