import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Scoreboard.module.css";
import firebase from "../config/firebase";
import React, { useState, useEffect } from "react";

export default function Home() {
  const [triggerpermission, setTriggerpermission] = useState(0);
  useEffect(() => {
    firebase
      .firestore()
      .collection("triggerID")
      .doc("TriggerPermission")
      .onSnapshot((documentSnapshot) => {
        // console.log("DOCSNAP " + JSON.stringify(documentSnapshot));
        console.log("DOCSNAP " + JSON.stringify(documentSnapshot.data()));
        console.log("DOCSNAP " + documentSnapshot.data().permissionID);
        let permissionID = documentSnapshot.data().permissionID;
        setTriggerpermission(permissionID);
      });
  }, []);

  return (
    <>
      {triggerpermission == 0 ? (
        <>
          <div className={styles.containerwait}>
            <main className={styles.mainwait}>
              <h1 className={styles.titlewait}>
                Please {/* <Link href="/register"> */}
                <a>Register</a>
                {/* </Link> */}
              </h1>
            </main>
          </div>
        </>
      ) : (
        <>
          <div className={styles.container}>
            <Head>
              <title>ScoreBoard</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.header}>
              <h4 className={styles.headertitle}>SCOREBOARD</h4>
            </div>
            <div className={styles.leaderboard}></div>
            <main className={styles.main}>
              <div className={styles.nowleadercard}>
                <div className={styles.nowleadercardprofile}>
                  <p className={styles.nowleadercardprofilenum}>5</p>
                  <div className={styles.imagewrap}>
                    <img src="/i5.png"></img>
                    {/* <Image
                      priority={true}
                      src="/i5.png"
                      alt="Picture of the author"
                      width={50}
                      height={50}
                    /> */}
                  </div>

                  <p className={styles.nowleadercardprofilename}>Annop</p>
                </div>
                <div className={styles.nowleadercardscore}>
                  <p>50,000</p>
                </div>
              </div>

              <div className={styles.leadercard}>
                <div className={styles.leadercardprofile}>
                  <p className={styles.leadercardprofilenum}>1</p>
                  <div className={styles.imagewrap}>
                    <img src="/i1.png"></img>
                    {/* <Image
                      priority={true}
                      src="/i1.png"
                      alt="Picture of the author"
                      width={50}
                      height={50}
                    /> */}
                  </div>
                  <p className={styles.leadercardprofilename}>Peter</p>
                </div>
                <div className={styles.leadercardscore}>
                  <p>100,000</p>
                </div>
              </div>
              <div className={styles.leadercard}>
                <div className={styles.leadercardprofile}>
                  <p className={styles.leadercardprofilenum}>2</p>
                  <div className={styles.imagewrap}>
                    <img src="/i2.png"></img>
                    {/* <Image
                      priority={true}
                      src="/i2.png"
                      alt="Picture of the author"
                      width={50}
                      height={50}
                    /> */}
                  </div>
                  <p className={styles.leadercardprofilename}>Anakin</p>
                </div>
                <div className={styles.leadercardscore}>
                  <p>90,000</p>
                </div>
              </div>
              <div className={styles.leadercard}>
                <div className={styles.leadercardprofile}>
                  <p className={styles.leadercardprofilenum}>3</p>
                  <div className={styles.imagewrap}>
                    <img src="/i3.png"></img>
                    {/* <Image
                      priority={true}
                      src="/i3.png"
                      alt="Picture of the author"
                      width={50}
                      height={50}
                    /> */}
                  </div>
                  <p className={styles.leadercardprofilename}>Miranda</p>
                </div>
                <div className={styles.leadercardscore}>
                  <p>70,000</p>
                </div>
              </div>
              <div className={styles.leadercard}>
                <div className={styles.leadercardprofile}>
                  <p className={styles.leadercardprofilenum}>4</p>
                  <div className={styles.imagewrap}>
                    <img src="/i4.png"></img>
                    {/* <Image
                      priority={true}
                      src="/i4.png"
                      alt="Picture of the author"
                      width={50}
                      height={50}
                    /> */}
                  </div>
                  <p className={styles.leadercardprofilename}>Sonya</p>
                </div>
                <div className={styles.leadercardscore}>
                  <p>60,000</p>
                </div>
              </div>
              <div className={styles.leadercard}>
                <div className={styles.leadercardprofile}>
                  <p className={styles.leadercardprofilenum}>5</p>
                  <div className={styles.imagewrap}>
                    <img src="/i5.png"></img>
                    {/* <Image
                      priority={true}
                      src="/i5.png"
                      alt="Picture of the author"
                      width={50}
                      height={50}
                    /> */}
                  </div>
                  <p className={styles.leadercardprofilename}>Annop</p>
                </div>
                <div className={styles.leadercardscore}>
                  <p>50,000</p>
                </div>
              </div>
              <div className={styles.leadercard}>
                <div className={styles.leadercardprofile}>
                  <p className={styles.leadercardprofilenum}>6</p>
                  <div className={styles.imagewrap}>
                    <img src="/i6.png"></img>
                    {/* <Image
                      priority={true}
                      src="/i6.png"
                      alt="Picture of the author"
                      width={50}
                      height={50}
                    /> */}
                  </div>
                  <p className={styles.leadercardprofilename}>Ruzzy</p>
                </div>
                <div className={styles.leadercardscore}>
                  <p>40,000</p>
                </div>
              </div>
              <div className={styles.leadercard}>
                <div className={styles.leadercardprofile}>
                  <p className={styles.leadercardprofilenum}>7</p>
                  <div className={styles.imagewrap}>
                    <img src="/i7.png"></img>
                    {/* <Image
                      priority={true}
                      src="/i7.png"
                      alt="Picture of the author"
                      width={50}
                      height={50}
                    /> */}
                  </div>
                  <p className={styles.leadercardprofilename}>Aliza</p>
                </div>
                <div className={styles.leadercardscore}>
                  <p>30,000</p>
                </div>
              </div>
            </main>
          </div>
        </>
      )}
    </>
  );
}
