import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import firebase from "../config/firebase";
import React, { useState, useEffect } from "react";

export default function Home() {
  const [triggerpermission, setTriggerpermission] = useState(0);

  const setPermissionZero = () =>{
          firebase
            .firestore().collection("triggerID")
            .doc("TriggerPermission")
            .update({
              permissionID: 0,
            });
  }

    const setPermissionOne = () => {
          firebase
            .firestore()
            .collection("triggerID")
            .doc("TriggerPermission")
            .update({
              permissionID: 1,
            });
    };
  useEffect(() => {
    firebase
      .firestore()
      .collection("triggerID")
      .doc("TriggerPermission")
      .onSnapshot((documentSnapshot) => {
        // console.log("DOCSNAP " + JSON.stringify(documentSnapshot));
        console.log("DOCSNAP " + JSON.stringify(documentSnapshot.data()));
        console.log("DOCSNAP " + documentSnapshot.data().permissionID);
        let permissionID = documentSnapshot.data().permissionID;
        setTriggerpermission(permissionID);
      });
  }, [triggerpermission]);


  return (
    <div className={styles.container}>
      <Head>
        <title>Trigger Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Now Permission {triggerpermission}</h1>
      <button onClick={setPermissionZero} type="button">
        Set Zero
      </button>
      <button onClick={setPermissionOne} type="button">
        Set One
      </button>
    </div>
  );
}
